In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#create dataframe from numpy
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [16]:
#creating arrays
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 9, 9, 1, 3],
       [8, 1, 3, 3, 7],
       [6, 8, 5, 8, 7]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.40354081, 0.08503792, 0.67878169],
       [0.64934317, 0.2968896 , 0.71809925],
       [0.94776961, 0.13048915, 0.63160249],
       [0.40463201, 0.54886877, 0.99196018],
       [0.12532721, 0.24253525, 0.87356624]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.88375314, 0.14255277, 0.13881006],
       [0.63004881, 0.59185723, 0.01659101],
       [0.1062162 , 0.24381119, 0.54676813],
       [0.22952755, 0.24781694, 0.42524785],
       [0.55996453, 0.6855928 , 0.27245729]])

In [33]:
#psuedo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_array_4.shape

(5, 3)

In [34]:
#viewing arrays and matrices
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1[0]

1

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a3[:2, :2, :2] #first 2 values of each floor, row, col

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [42]:
a4[:, :, :, :2] #slice all of dim 1 to 3 but first 2 of 4th dim

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

In [47]:
#use python's methods on python datatypes
#use numpy's methods on numpy datatypes
massive_array = np.random.random(100000) #np method
massive_array.size, massive_array[:10]

(100000,
 array([0.22204305, 0.92063245, 0.75837437, 0.58956424, 0.38768665,
        0.63767413, 0.72639352, 0.18929253, 0.40308868, 0.00768898]))

In [45]:
%timeit sum(massive_array) #python's sum()
%timeit np.sum(massive_array) #np's sum()

8.42 ms ± 509 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.3 µs ± 784 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
#reshaping and transposing
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [49]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [51]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [52]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [53]:
#transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [54]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [55]:
#dot product
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [56]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [57]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [58]:
#element-wise multiplication (top left * top left, etc...)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [62]:
#dot product (3x3 dot 3x2) = (3x2) -> outputs total of rate*qty for each item
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [64]:
#ex nut butter sales
np.random.seed(0) #number of jars sold
sales_amounts = np.random.randint(20, size=(5,3)) #5 days a week, 3 types of butter
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [65]:
#create dataframe
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [66]:
#create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [69]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), #reshape needed bc prices in (3 rows, 1) - 1 dim view only
                           index=["Price"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [70]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [71]:
#create daily_sales
daily_sales = butter_prices.dot(weekly_sales.T) #(1x3)x(3x5)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [72]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

<img src="images/panda.png"/>

In [77]:
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [78]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [79]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [83]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [84]:
car[:1] #first row only

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)